#!/bin/bash

# Deployment troubleshooting script
echo "🚀 Deployment Troubleshooting Guide"
echo "======================================"

echo ""
echo "📋 Environment Variables Check:"
echo "- DATABASE_URL: ${DATABASE_URL:+✅ Set} ${DATABASE_URL:-❌ Not set}"
echo "- NEXTAUTH_URL: ${NEXTAUTH_URL:+✅ Set} ${NEXTAUTH_URL:-❌ Not set}"
echo "- NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:+✅ Set} ${NEXTAUTH_SECRET:-❌ Not set}"
echo "- BLOB_READ_WRITE_TOKEN: ${BLOB_READ_WRITE_TOKEN:+✅ Set} ${BLOB_READ_WRITE_TOKEN:-❌ Not set}"
echo "- NODE_ENV: ${NODE_ENV:-development}"

echo ""
echo "🔧 Common Deployment Issues & Solutions:"
echo ""
echo "1. 'Unexpected token <' error:"
echo "   - This happens when API routes return HTML instead of JSON"
echo "   - Usually caused by authentication middleware blocking requests"
echo "   - Or database connection failures in production"
echo ""
echo "2. Database connection issues:"
echo "   - Ensure DATABASE_URL is correctly formatted"
echo "   - Check if connection pooling is properly configured"
echo "   - Verify SSL settings for production databases"
echo ""
echo "3. Authentication failures:"
echo "   - Verify NEXTAUTH_URL matches your deployment domain"
echo "   - Ensure NEXTAUTH_SECRET is at least 32 characters"
echo "   - Check OAuth provider settings for production URLs"
echo ""
echo "4. File upload issues:"
echo "   - Verify BLOB_READ_WRITE_TOKEN is set correctly"
echo "   - Check Vercel Blob storage permissions"
echo "   - Ensure middleware allows upload endpoints"
echo ""
echo "📝 Quick Fixes:"
echo ""
echo "1. Add to your deployment environment variables:"
echo "   NEXTAUTH_URL=https://yourdomain.com"
echo "   NEXTAUTH_SECRET=your-32-char-secret"
echo "   DATABASE_URL=your-production-db-url"
echo "   BLOB_READ_WRITE_TOKEN=your-vercel-blob-token"
echo ""
echo "2. Test API endpoints after deployment:"
echo "   curl https://yourdomain.com/api/debug/deployment"
echo "   curl https://yourdomain.com/api/health"
echo ""
echo "3. Check build logs for any missing dependencies"
echo "4. Verify database migrations ran successfully"
